// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'storage/service_provider_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2951548079412544867),
    name: 'ServiceProviderModel',
    lastPropertyId: const obx_int.IdUid(7, 2879477077982844045),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6141354969995594970),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3863564126040356639),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1270541120429749471),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1392747508046816665),
        name: 'skills',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7988602400938286736),
        name: 'lat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1716980722085854160),
        name: 'long',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2879477077982844045),
        name: 'phonenumber',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2951548079412544867),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ServiceProviderModel: obx_int.EntityDefinition<ServiceProviderModel>(
      model: _entities[0],
      toOneRelations: (ServiceProviderModel object) => [],
      toManyRelations: (ServiceProviderModel object) => {},
      getId: (ServiceProviderModel object) => object.id,
      setId: (ServiceProviderModel object, int id) {
        object.id = id;
      },
      objectToFB: (ServiceProviderModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final addressOffset = fbb.writeString(object.address);
        final skillsOffset = fbb.writeList(
          object.skills.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, addressOffset);
        fbb.addOffset(3, skillsOffset);
        fbb.addFloat64(4, object.lat);
        fbb.addFloat64(5, object.long);
        fbb.addInt64(6, object.phonenumber);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final skillsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final latParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final longParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final phonenumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = ServiceProviderModel(
          name: nameParam,
          address: addressParam,
          skills: skillsParam,
          lat: latParam,
          long: longParam,
          phonenumber: phonenumberParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ServiceProviderModel] entity fields to define ObjectBox queries.
class ServiceProviderModel_ {
  /// See [ServiceProviderModel.id].
  static final id = obx.QueryIntegerProperty<ServiceProviderModel>(
    _entities[0].properties[0],
  );

  /// See [ServiceProviderModel.name].
  static final name = obx.QueryStringProperty<ServiceProviderModel>(
    _entities[0].properties[1],
  );

  /// See [ServiceProviderModel.address].
  static final address = obx.QueryStringProperty<ServiceProviderModel>(
    _entities[0].properties[2],
  );

  /// See [ServiceProviderModel.skills].
  static final skills = obx.QueryStringVectorProperty<ServiceProviderModel>(
    _entities[0].properties[3],
  );

  /// See [ServiceProviderModel.lat].
  static final lat = obx.QueryDoubleProperty<ServiceProviderModel>(
    _entities[0].properties[4],
  );

  /// See [ServiceProviderModel.long].
  static final long = obx.QueryDoubleProperty<ServiceProviderModel>(
    _entities[0].properties[5],
  );

  /// See [ServiceProviderModel.phonenumber].
  static final phonenumber = obx.QueryIntegerProperty<ServiceProviderModel>(
    _entities[0].properties[6],
  );
}
